from __future__ import annotations

import json
from typing import Iterable

from .base import AdapterCapabilities, AdapterFile, CoreSkill, HarnessAdapter


RULE_PATH = ".claude/rules/scrumaidev.md"


class ClaudeCodeAdapter(HarnessAdapter):
    """Claude Code adapter using project Skills and a dedicated project rule.

    Claude Code discovers project skills only under `.claude/skills` (not
    `.agents/skills`) and does not guarantee reading `AGENTS.md` when the
    project has its own `CLAUDE.md`. This adapter therefore emits:

    - `.claude/rules/scrumaidev.md`: a persistent bridge to `AGENTS.md` and
      `.scrumaidev/AGENTS.md` that never touches the user's `CLAUDE.md`;
    - one thin workflow skill per canonical workflow;
    - one thin facade per shared specialist skill.

    Canonical content stays in `.agents/workflows` and `.agents/skills`.
    Facades declare no `model`, `context`, `agent` or `allowed-tools`, so the
    session model, the main conversation (human gates) and the user's
    permission settings are preserved.
    """

    id = "claude"
    display_name = "Claude Code"
    capabilities = AdapterCapabilities(
        commands=False,  # skills are the recommended primitive; no `.claude/commands`
        skills=True,
        project_instructions=True,
        hooks=False,
        subagents=False,
        multi_install_safe=True,
    )

    @staticmethod
    def _skill_name(name: str) -> str:
        return f"scrumaidev-{name}"

    @staticmethod
    def _yaml_string(value: str) -> str:
        # JSON string syntax is a valid YAML double-quoted scalar.
        return json.dumps(value, ensure_ascii=False)

    def _rule(self, workflows: list[str]) -> bytes:
        rows = "\n".join(
            f"| `/{workflow}` | `/{self._skill_name(workflow)}` |" for workflow in workflows
        )
        body = f"""# ScrumAIDev

Generated by `scrumaidev config --harness claude`. Do not edit: `scrumaidev doctor` tracks this file by hash and `scrumaidev uninstall` removes it.

This project is configured with ScrumAIDev. Project instructions:

@../../AGENTS.md

## Operating contract

- Follow the project `AGENTS.md` (imported above). If it was not loaded into context, read `AGENTS.md` before ScrumAIDev-governed work.
- Read `.scrumaidev/AGENTS.md` and follow it as the canonical ScrumAIDev operating contract.
- Canonical workflows live in `.agents/workflows/<workflow>.md` and canonical specialist skills in `.agents/skills/<skill>/SKILL.md`. The `.claude/skills/scrumaidev-*` skills are thin facades that point to them.
- Preserve the model already selected in the current Claude Code session. ScrumAIDev does not select or override a model.
- Never auto-approve a human review/approval gate defined by a canonical workflow; stop at the gate and ask for the required decision.
- The ScrumAIDev commit rules in `AGENTS.md` take precedence over default commit attribution: do not add a `Co-authored-by:` trailer for an AI agent.

## Invocation in Claude Code

Canonical ScrumAIDev documents refer to workflows as `/<workflow>`. In Claude Code, the user invokes them as:

| Canonical | Claude Code |
|---|---|
{rows}

When a canonical workflow routes to another workflow, tell the user the Claude Code invocation above, or read the target `.agents/workflows/<workflow>.md` directly when the user asks you to continue.

Shared specialist skills (for example `architect` or `qa-engineer`) are exposed as `scrumaidev-<skill>`.
"""
        return body.encode("utf-8")

    def _workflow_skill(self, workflow: str) -> bytes:
        skill = self._skill_name(workflow)
        description = self._yaml_string(f"ScrumAIDev workflow: {workflow}")
        body = f"""---
name: {skill}
description: {description}
argument-hint: "[workflow input]"
disable-model-invocation: true
---

# ScrumAIDev — {workflow}

Execute the canonical ScrumAIDev workflow `{workflow}`.

1. Read `.agents/workflows/{workflow}.md` completely before acting.
2. Treat that workflow file as the canonical process definition; do not replace it with this skill facade.
3. Follow the project `AGENTS.md` chain and `.scrumaidev/AGENTS.md` as the ScrumAIDev operating contract.
4. Use the user arguments below and the current conversation as the workflow input; preserve any constraints already stated.
5. Preserve the model already selected in the current Claude Code session. This skill does not select or override a model.
6. If the canonical workflow requires an explicit human review/approval gate, stop at that gate and ask for the required decision instead of auto-approving it.
7. When the canonical workflow refers to another workflow as `/<workflow>`, the Claude Code invocation is `/scrumaidev-<workflow>`.

Canonical workflow: `.agents/workflows/{workflow}.md`

User arguments: $ARGUMENTS
"""
        return body.encode("utf-8")

    def _specialist_skill(self, skill: CoreSkill) -> bytes:
        name = self._skill_name(skill.name)
        canonical = f".agents/skills/{skill.name}/SKILL.md"
        description = self._yaml_string(
            skill.description or f"ScrumAIDev specialist skill: {skill.name}"
        )
        body = f"""---
name: {name}
description: {description}
---

# ScrumAIDev specialist skill — {skill.name}

Thin Claude Code facade for the canonical ScrumAIDev specialist skill `{skill.name}`.

1. Read `{canonical}` completely and follow it as the canonical skill definition; do not replace it with this facade.
2. Resolve any relative path mentioned by the canonical skill against `.agents/skills/{skill.name}/`.
3. Follow the project `AGENTS.md` chain and `.scrumaidev/AGENTS.md` as the ScrumAIDev operating contract.
4. Preserve the model already selected in the current Claude Code session. This skill does not select or override a model.
5. Never auto-approve a human review/approval gate; stop and ask for the required decision.

Canonical skill: `{canonical}`

User arguments: $ARGUMENTS
"""
        return body.encode("utf-8")

    def files(self, workflows: Iterable[str]) -> list[AdapterFile]:
        ordered = sorted(workflows)
        result = [AdapterFile(RULE_PATH, self._rule(ordered))]
        for workflow in ordered:
            result.append(
                AdapterFile(
                    f".claude/skills/{self._skill_name(workflow)}/SKILL.md",
                    self._workflow_skill(workflow),
                )
            )
        return result

    def skill_files(self, skills: Iterable[CoreSkill]) -> list[AdapterFile]:
        return [
            AdapterFile(
                f".claude/skills/{self._skill_name(skill.name)}/SKILL.md",
                self._specialist_skill(skill),
            )
            for skill in sorted(skills, key=lambda s: s.name)
        ]

    def invocation(self, workflow: str) -> str:
        return f"/{self._skill_name(workflow)}"

    def cleanup_roots(self) -> tuple[str, ...]:
        # Uninstall removes only unchanged manifest-tracked files, then rmdir()s
        # empty directories bottom-up. Any user content (settings.json,
        # settings.local.json, own rules/skills, CLAUDE.md) keeps `.claude/`.
        return (".claude",)
